name: Deploy

on:
  push:
    branches:
      - main

env:
  node_version: 14

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run deploy
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNTID: ${{ secrets.CLOUDFLARE_ACCOUNTID }}
          CLOUDFLARE_ZONEID: ${{ secrets.CLOUDFLARE_ZONEID }}
